version: 1.0.{build}

image: Visual Studio 2017
configuration: Release

environment:
 matrix:
    - PLATFORM: x64
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_ROOT: C:\Libraries\boost_1_66_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_66_0\lib64-msvc-14.1
    - PLATFORM: x86
      BUILDER: CMake
      GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BOOST_ROOT: C:\Libraries\boost_1_66_0
      BOOST_LIBRARYDIR: C:\Libraries\boost_1_66_0\lib32-msvc-14.1
      
before_build:
     - ps: 'Write-Host "Running $env:BUILDER with $env:GENERATOR" -ForegroundColor Magenta'
     - if "%BUILDER%"=="CMake" cmake.exe -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%CONFIGURATION% %APPVEYOR_BUILD_FOLDER%
     
build_script:
   - ps: 'Write-Host "Running $env:BUILDER:" -ForegroundColor Magenta'
   - md build && cd build
   - if "%BUILDER%"=="CMake" cmake --build . --config %CONFIGURATION%

